
server:
    port: 8080
    servlet:
      context-path: /intern

spring:
    datasource:
        url: "jdbc:postgresql://localhost:5432/postgres"
        username: postgres
        password: 123456

jwt:
    signerKey: "RohsA+YZeqwYeCN5N6Kg3JglXNUZng1qi3+FgZHLffpnALIHBdr0EWdHvd5RI7TV"
    valid-duration: 1000 # in second
    refreshable-duration: 120 # in seconds
#    jpa:
#        hibernate:
#            ddl-auto: update
#        show-sql: true




