
server:
    port: 8080
    servlet:
      context-path: /intern

spring:
    datasource:
        url: "jdbc:postgresql://localhost:5432/postgres"
        username: postgres
        password: 123456

    mail:
        host: smtp.gmail.com
        port: 587
        username: wonwon5800@gmail.com
        password: mxrm tgfr efgi rdml
        properties:
            mail:
                transport:
                    protocol: smtp
                smtp:
                    auth: true
                    starttls:
                        enable: true

jwt:
    signerKey: "RohsA+YZeqwYeCN5N6Kg3JglXNUZng1qi3+FgZHLffpnALIHBdr0EWdHvd5RI7TV"
    api-prefix: "api/v1"
    valid-duration: 1000 # in second
    refreshable-duration: 3600 # in seconds
#    jpa:
#        hibernate:
#            ddl-auto: update
#        show-sql: true




